apiVersion: v1
kind: Service
metadata:
  name: goldcalc-service
  namespace: goldapp
spec:
  type: NodePort
  selector:
    app: goldcalc
  ports:
  - name: http               # ðŸ”¥ MUST ADD THIS
    port: 5000
    targetPort: 5000
    nodePort: 30080


